apiVersion: v1
kind: Service
metadata:
  name: mailchimp-trends-backend-svc # mailchimp-trends-backend-svc as per story guidance
  labels:
    app: mailchimp-trends-backend
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port (the NodePort).
  selector:
    app: mailchimp-trends-backend # Must match the labels of the backend Deployment's pods
  ports:
  - name: http
    port: 8000 # Port the service will be available on within the cluster
    targetPort: 8000 # Port the backend container is listening on
    nodePort: 30800 # Fixed NodePort for host accessibility
    protocol: TCP
